name = "ServerName"
user = "mongo"
japd = None
host = "hostname"
port = 27017
auth = False
auth_db = "admin"
repset = "ReplicaSet"
repset_hosts = ["host1:27017", "host2:27017"]
auth_mech = "SCRAM-SHA-1"
ssl_client_ca = None
ssl_client_cert = None
ssl_client_key = None
ssl_client_phrase = None
